### ISSUE TITLE
Universal Shortcode

### ISSUE THREAD

**Issue by rcopstein** [takanorip/eleventy-google-fonts#1]
I see that the plugin specifically adds a shortcode for Nujuck. Since version 0.7 eleventy supports universal shortcodes that support all template languages. I am not 100% sure how `async` support works on universal shortcodes, but at least giving support for Liquid and JavaScript (both of which support asynchronous methods) would be a big plus!

**Comment by takanorip** [comment]
Fixed
https://github.com/takanorip/eleventy-google-fonts/pull/2
